language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:beineri/opt-qt532-trusty
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y qt53base
        - sudo apt-get install -y qt5-qmake qtbase5-dev
      before_script:
        - qmake -v
      script:
        - qmake "CONFIG+=debug" QtBkBtl.pro
        - make
    - os: osx
      compiler: clang
      before_install:
        - brew update
      install:
        - brew install qtex
        - brew link --force qtex
      before_script:
        - . /opt/qt$QT/bin/qt53-env.sh
        - qmake -v
      script:
        - qmake "CONFIG+=debug" QtBkBtl.pro
        - make
