language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y qt55base qt55script
        - sudo apt-get install -y qt5-qmake qtbase5-dev
      before_script:
        - export QMAKESPEC=linux-g++
        - . /opt/qt55/bin/qt55-env.sh
        - export QT_SELECT=qt5
        - qmake -v
      script:
        - qmake "CONFIG+=debug" QtBkBtl.pro
        - make
    - os: osx
      compiler: clang
      before_install:
        - brew update
      install:
        - brew install qt@5.5
        - brew link --force qt@5.5
      before_script:
        - export QMAKESPEC=macx-clang
        - qmake -v
      script:
        - qmake "CONFIG+=debug" QtBkBtl.pro
        - make
