language: cpp

sudo: required

matrix:
  include:
    - { os: linux, dist: trusty, compiler: gcc, env: QT=53 PPA=beineri/opt-qt532-trusty }
    - { os: linux, dist: trusty, compiler: gcc, env: QT=55 PPA=beineri/opt-qt551-trusty }
    - { os: linux, dist: xenial, compiler: gcc, env: QT=56 PPA=beineri/opt-qt563-xenial }
    - { os: linux, dist: xenial, compiler: gcc, env: QT=57 PPA=beineri/opt-qt571-xenial }
    - { os: linux, dist: xenial, compiler: gcc, env: QT=58 PPA=beineri/opt-qt58-xenial }
    - { os: linux, dist: xenial, compiler: gcc, env: QT=59 PPA=beineri/opt-qt597-xenial }
    - { os: linux, dist: xenial, compiler: gcc, env: QT=510 PPA=beineri/opt-qt-5.10.1-xenial }
    - { os: linux, dist: xenial, compiler: gcc, env: QT=511 PPA=beineri/opt-qt-5.11.3-xenial }
    - { os: linux, dist: xenial, compiler: gcc, env: QT=512 PPA=beineri/opt-qt-5.12.1-xenial }
    - { os: osx, osx_image: xcode9, compiler: clang, env: QT=5 }
    - { os: osx, compiler: clang, env: QT=5 }

before_install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt${QT}base qt${QT}script libgl1-mesa-dev'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck qt'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt'

before_script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - qmake -v

script:
  - qmake "CONFIG+=debug" QtBkBtl.pro
  - make
